### ISSUE TITLE
Detailed race not appearing in eCR3.0 CCDA

### ISSUE THREAD

**Issue by rashmi1977** [drajer-health/eCRNow#651]
In EMR products we have the option of capturing both Race and Detaield Race(Race 2). Please see screen below
<img width="629" alt="Race EMR" src="https://github.com/drajer-health/eCRNow/assets/60920244/047c9b8a-2344-4057-ae69-6c0e0e8a7d89">
After entering detailed race we get the same in GET response of Patient FHIR resource. Please see screen below
<img width="710" alt="Race FHIR response" src="https://github.com/drajer-health/eCRNow/assets/60920244/7d5a8c35-f4e8-4df3-b425-25897f6ca016">
But in the eCR3.0 CCDA we do not see the detailed Race. Please find attached 
[eCR 3.0 Race_CCDA.txt](https://github.com/drajer-health/eCRNow/files/14217704/eCR.3.0.Race_CCDA.txt)
the eCR3.0 CCDA which does not have detailed race-It is an eCR CCDA generated on eCR version 3.0

**Comment by AGABB** [comment]
Hello @rashmi1977 - 

The eICR 1.1 IG Specifies "This patient SHALL contain exactly one [1..1] raceCode, which SHALL be selected from ValueSet Race Category Excluding Nulls"

In the example you shared, both the 2028-9 and 2054-5 codes are from the ValueSet Race Category Excluding Nulls.

The FHIR App includes the first raceCode that has an extension url of http://hl7.org/fhir/us/core/StructureDefinition/us-core-race and child extension of ombCategory by design, that is why you are just seeing the first code in the eICR. 

CC: @nbashyam

**Comment by rashmi1977** [comment]
Yes the desired behavior would be for the second race to be included in the sdtc:raceCode element.In the above example i am expecting the second race ie 2054-5 to be included in eCR CCDA.

**Comment by nbashyam** [comment]
Not sure we can incldue that in the sdtc:raceCode element as it is not the detailed race code element.

**Comment by rashmi1977** [comment]
As per the below sample CCDA generated CCDA from our client, when a patient has both race and detailed race,it is displayed in the below format and NIST CCDA validator tool does bot error out this implementation
<img width="896" alt="image" src="https://github.com/drajer-health/eCRNow/assets/60920244/afc6b27e-0cf5-4c6c-bb5d-e1cbebb5ce02">
Can we have the similar implementation in eCR as well

**Comment by rashmi1977** [comment]
With recent code of eCR3.1.3 we found that we are not able to see the detailed race as expected
Detailed race Native Hawaian or Other Pacific captured in client.
![image](https://github.com/drajer-health/eCRNow/assets/60920244/04a6b1e3-ca29-436c-a47b-cc83aee0083b)
Unable to see detailed race in eCR CCDA with eCR3.1.3 code
![image](https://github.com/drajer-health/eCRNow/assets/60920244/e04a7397-028f-4425-8b7d-b0b864ec6c28)
As per the IG of eCR example we need to get detailed race as below
![image](https://github.com/drajer-health/eCRNow/assets/60920244/0eec169f-fc5c-4d07-983c-a2b008aa3ed9)

**Comment by VenkatSaiReddyTeegala** [comment]
Resolved as part of 3.1.4

**Comment by rashmi1977** [comment]
We are still seeing the same issue with 3.1.4 build. We are not finding the detailed race in the eCR XML. Attaching XML for reference.
![image](https://github.com/drajer-health/eCRNow/assets/60920244/e61affa9-c160-4182-9903-ad9b198fb543)
We are getting detailed ethnicity and not detailed race. Please refer the attached screenshot above.

**Comment by mmatiasalt** [comment]
@rashmi1977 I opened a new ticket since this one is closed https://github.com/drajer-health/eCRNow/issues/749
