### ISSUE TITLE
EICR Results Section Text- Row data and Column Header not matching

### ISSUE THREAD

**Issue by ShubhamAnand992** [drajer-health/eCRNow#82]
In the results section of the EICR document generated through application, text has 3 columns in the table. The order in which the table columns appear is not in sync with the order in which the table data is displayed. This happens due to the use of HashMap [CdaTesultsGenerator, Method-generateResultsSection] to store row values.

Code Snippet:

         for (Observation obs : results) {

        String obsDisplayName = CdaGeneratorConstants.UNKNOWN_VALUE;
        List<Coding> cds = null;
        if (obs.getCode() != null && obs.getCode().getCodingFirstRep() != null) {

          cds = obs.getCode().getCoding();

          if (!StringUtils.isEmpty(obs.getCode().getCodingFirstRep().getDisplay())) {
            obsDisplayName = obs.getCode().getCodingFirstRep().getDisplay();
          } else if (!StringUtils.isEmpty(obs.getCode().getText())) {
            obsDisplayName = obs.getCode().getText();
          }
        }

        Map<String, String> bodyvals = new HashMap<>();
        bodyvals.put(CdaGeneratorConstants.LABTEST_TABLE_COL_1_BODY_CONTENT, obsDisplayName);

        String val = CdaGeneratorConstants.UNKNOWN_VALUE;
        if (obs.getValue() != null) {

          val = CdaFhirUtilities.getStringForType(obs.getValue());
        }

**Comment by nbashyam** [comment]
Updates pushed to baseline.

**Comment by AnanthaKrishnaV** [comment]
![image](https://user-images.githubusercontent.com/28885907/104939989-2051bb00-59d7-11eb-8172-3835a360fcb3.png)

Issue still exists

**Comment by nbashyam** [comment]
Please retest. This should be fixed per 1/19 baseline.

**Comment by AnanthaKrishnaV** [comment]
I have tested with the 1/19 baseline, it's still not working. Can you point me to the code changes for this fix?

![image](https://user-images.githubusercontent.com/28885907/105728869-a0859c80-5f52-11eb-9ff9-6a4ec3257819.png)

**Comment by nbashyam** [comment]
I did not notice the mismatch in the headers, sorry about that ..we had just tried changing the strings...i will look into it.

**Comment by nbashyam** [comment]
Please retest, this should be addressed now.
