### ISSUE TITLE
Unit Test Failures on Case Sensitive File Systems (Linux)

### ISSUE THREAD

**Issue by medhost-chara** [drajer-health/eCRNow#916]
The following Test will fail on linux based file systems as they are case sensitive:

**Test: CdaOdhDataGeneratorTest**
Following Filenames do not match the unit tests:
src/test/resources/CdaTestData/Cda/odh/odh.xml
src/test/resources/CdaTestData/Cda/odh/EmptyOdh.xml

private static final String ODH_CDA_FILE = "CdaTestData/Cda/**Odh**/odh.xml";
private static final String EMPTY_ODH_CDA_FILE = "CdaTestData/Cda/odh/**emptyOdh**.xml";

Causing Build Server Failure:
[main] ERROR com.drajer.test.util.TestUtils - File not found::CdaTestData/Cda/odh/emptyOdh.xml
[main] ERROR com.drajer.test.util.TestUtils - File not found::CdaTestData/Cda/Odh/odh.xml

**Test: Dstu2CdaEncounterGeneratorTest**
src/test/resources/CdaDstuTestData/**cda**/Encounter/**Encounter**.xml
src/test/resources/CdaDstuTestData/**cda**/Encounter/emptyEncounter.xml

private static final String ENCOUNTER_CDA_FILE = "CdaDstuTestData/**Cda**/Encounter/**encounter**.xml";
private static final String EMPTY_ENCOUNTER_CDA_FILE =
      "CdaDstuTestData/**Cda**/Encounter/emptyEncounter.xml";

**Comment by nbashyam** [comment]
Add to 3.1.10

**Comment by nbashyam** [comment]
Fixed in 3.1.10

**Comment by medhost-chara** [comment]
This is not fixed. Reopening https://github.com/drajer-health/eCRNow/issues/949
