### ISSUE TITLE
if we start too many eCS containers for ECRNow they will deadlock against each other waiting on database.

### ISSUE THREAD

**Issue by NaveenKoujalagi** [drajer-health/eCRNow#972]
It appears in eCR 1.4 the new eCRNow version introduced a Postgres DB Query at startup that is non-performant, and was failing healthchecks on the containers as they deadlocked waiting on the database/each other. 

We had 20 containers running in prod, and they were all just cycling into unhealthy hosts. 
During investigation we found that they seem to be concurrently causing deadlocks against postgres - see below. Once we stopped all containers for eCRNow, note the deadlocks stopped. 

![Image](https://github.com/user-attachments/assets/91e97cbc-e2bd-472b-9a07-3e7dd1ccc537)

SQL Query: 

update healthcare_setting set aa_id=$1, auth_type=$2, backend_auth_key_alias=$3, clientId=$4, clientSecret=$5, create_doc_ref_response=$6, debug_enabled=$7, default_provider_id=$8, direct_host=$9, direct_pwd=$10, direct_recipient_address=$11, smtp_tls_version=$12, direct_user=$13, doc_ref_mime_type=$14, ehr_access_token=$15, token_expiry_date=$16, ehr_access_token_expiry_duration=$17, ehr_supports_subscriptions=$18, encounter_end_time=$19, encounter_start_time=$20, is_fhir=$21, fhir_server_base_

As part of our analysis, we investigated critical startup failures in eCRNow version 3.1.8, which were traced to uncoordinated container behavior leading to PostgreSQL deadlocks and container restarts.

**Summary of the Defect:**

1. All eCRNow containers independently invoked saveOrUpdate() on the same healthcare_setting row, regardless of whether data had changed.
2. Simultaneously, each container started a db-scheduler instance that attempted to revive the same set of tasks.
3. This behavior led to row-level lock contention, scheduler conflicts, and ultimately connection pool starvation.
4. These issues created a cascading failure scenario that affected container health, system availability, and eICR processing reliability.

**Our Findings (Highlights):**

- The retrieveAndUpdateAccessToken() method performs unconditional updates, which are avoidable through change detection logic.

- Multiple containers revive the same dead execution, leading to errors like: ExecutionException: Expected one execution to be updated, but updated 0

- Startup concurrency causes schema migration collisions, and together these factors degrade system stability.

**Proposed Actions (Request to Drajer Team):**

We request the Drajer team to review and consider implementing the following changes in the core eCRNow codebase:

1. **Enhance Access Token Update Logic**

Add conditional logic before invoking saveOrUpdate() to prevent unnecessary writes and avoid deadlocks.
? A sample code fix is provided in this report under Recommended Fix.

2. **Control db-scheduler Execution**

Ensure only one container initializes the db-scheduler using property flags like:
db-scheduler.enabled = false // for most containers
This avoids concurrent revive attempts.

3. **Improve Fault Tolerance**

Add backoff strategies and error handling for scheduler revive logic to reduce retry storms.

4. **Disable Auto-DDL Execution**

Adopt a migration tool like Flyway or Liquibase to control schema evolution in multi-container deployments.

**We would appreciate it if the Drajer team could validate our analysis and let us know if this aligns with your understanding of the system. If so, the actions above would help ensure smoother container startup and overall stability in future releases.**

**Comment by ArshadBanglewale** [comment]
Hi @nbashyam,
Following up on this ticket, this fix was supposed to be included in eCRNow 3.1.14, but we don’t see the changes in that release.
Could you please confirm whether the fix actually made it into 3.1.14?
If so, can you point us to the commit or configuration change?
If not, what release is this now planned for?

**Comment by ArshadBanglewale** [comment]
Hi @nbashyam,
Just following up on my earlier message regarding this ticket. The fix was expected to be included in eCRNow 3.1.14, but we’re not seeing the changes in that release.
Could you please confirm:

Was the fix included in 3.1.14?

If yes, could you point us to the commit or configuration change?


If not, which release is it now planned for?

Thanks for your help!

**Comment by bhargavchowdhary** [comment]
@ArshadBanglewale 
We will investigate the deadlock issue and attempt to reproduce it on the latest version. If the issue is not present, you can proceed with the upgrade and I will share the upgrade details. If any issues are identified, we will address them as part of the next release.

**Comment by neharastogi** [comment]
Hello @nbashyam , We also encountered similar error when we deployed v3.1.14 to our prod instances. 

Initially the application was fine when we had 3 ECS tasks but as soon as it scaled up to 10, we started seeing errors in the tasks when connecting to the database. 
These are the errors we saw in the database logs during that time - 

`could not accept SSL connection: A system call failed on the socket. Errno:Success`
`FATAL:  canceling authentication due to timeout`

Can you please help us with the next steps.

**Comment by NaveenKoujalagi** [comment]
Hi @nbashyam We are still seeing container issue after eCR Now 4.0.2 upgrade and hence some sites are finding feed issue.

Every time manual restart is the difficult task
